version: '3'

services:
  api:
    environment:
      COURSES_DIR: /courses
    volumes:
      - /courses:/courses

  front:
    ports:
      - '80:8080'
    environment:
      API_URL: http://204.48.18.156:3000
